### ISSUE TITLE
acm case sensitivy

### ISSUE THREAD

**Issue by runekaagaard** [manateelazycat/lsp-bridge#800]
Hi, thx for a great project, I'm moving away from lsp-mode and the performance is a breath of fresh air!

Are there a way to make acm case sensitive, so when using eg. pyright lsp server I only get completions that matches the case of whats being searched for?

**Comment by manateelazycat** [comment]
acm menu show candidates in realtime that return by lsp server.

acm don't filter candidates for performance, if you want filter candidates, you should use acm-filter command (Alt + u when popup acm menu)

lsp-bridge don't filter candidates on elisp side because elisp's poor performance, If you really want filter candidates with some rule, you should hacking https://github.com/manateelazycat/lsp-bridge/blob/f628c05e8daf82d1cd135fe3a4102a1c7f8667b7/core/handler/completion.py#L165

**Comment by runekaagaard** [comment]
Hi again, thx for your reply. This seems to do exactly that:

```
--- completion-before.py	2023-11-29 18:29:42.100195888 +0100
+++ completion.py	2023-11-29 18:25:21.711380772 +0100
@@ -131,6 +131,14 @@
                 if fuzzy and not string_match(label.lower(), self.prefix.lower(), fuzzy=fuzzy):
                     continue
 
+                # TODO: Get this from an emacs variable like acm-case-sensitivity.
+                ACM_CASE_SENSITIVITY = True
+
+                # If acm-case-sensitivity is t, ensure that the label starts with prefix. We only enforce this rule for non-fuzzy
+                # searches.
+                if ACM_CASE_SENSITIVITY and not fuzzy and not string_match(label, self.prefix, fuzzy=fuzzy):
+                    continue
+
                 annotation = kind if kind != "" else detail
```

Would you be interested in a PR that introduces a defcustom variable to acm, or do you consider it out of scope?

**Comment by manateelazycat** [comment]
Looks like you want candidates only match input prefix?

**Comment by manateelazycat** [comment]
I have push https://github.com/manateelazycat/lsp-bridge/commit/c6761b1977d670017ea02cce1d4263fa38562c37

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/lsp-bridge/commit/4150b07410f84cc19f9682af74ea1a6632f85d99

**Comment by runekaagaard** [comment]
You are the boss, thank you so much!!
